name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: modules/api
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Download deps
        run: go mod download

      - name: Build
        run: go build ./...

  frontend:
    name: Frontend (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: modules/web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Build
        env:
          # 仅用于构建期占位；不会访问后端
          API_SERVER: http://127.0.0.1:8080
        run: pnpm run build

      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: modules/web/dist
          if-no-files-found: ignore
